package com.puregoldgo.ibms.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF656100)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFF8EE00)
val onPrimaryContainerLight = Color(0xFF6F6B00)
val secondaryLight = Color(0xFF5F5F58)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFFDF4)
val onSecondaryContainerLight = Color(0xFF75756E)
val tertiaryLight = Color(0xFF1C684D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF3A8165)
val onTertiaryContainerLight = Color(0xFFF5FFF7)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFEFAE5)
val onBackgroundLight = Color(0xFF1D1C10)
val surfaceLight = Color(0xFFFEFAE5)
val onSurfaceLight = Color(0xFF1D1C10)
val surfaceVariantLight = Color(0xFFE8E3C5)
val onSurfaceVariantLight = Color(0xFF494832)
val outlineLight = Color(0xFF7B785F)
val outlineVariantLight = Color(0xFFCBC7AB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF323123)
val inverseOnSurfaceLight = Color(0xFFF5F1DC)
val inversePrimaryLight = Color(0xFFD4CB00)
val surfaceDimLight = Color(0xFFDEDAC6)
val surfaceBrightLight = Color(0xFFFEFAE5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F4DF)
val surfaceContainerLight = Color(0xFFF3EEDA)
val surfaceContainerHighLight = Color(0xFFEDE8D4)
val surfaceContainerHighestLight = Color(0xFFE7E3CF)
